# Generated by Django 3.0.3 on 2020-03-30 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('name', models.CharField(max_length=30, unique=True, verbose_name='course name')),
                ('course_id', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True, verbose_name='course id')),
                ('status', models.CharField(choices=[('floating', 'floating'), ('closed', 'closed')], max_length=20, verbose_name='status')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.department')),
                ('pre_requisites', models.ManyToManyField(blank=True, related_name='_course_pre_requisites_+', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='time_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.ManyToManyField(to='courses.course')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.period_slot')),
            ],
        ),
        migrations.CreateModel(
            name='course_ta_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('action', models.CharField(choices=[('joined', 'joined'), ('left', 'left')], max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.ta')),
            ],
        ),
        migrations.CreateModel(
            name='course_student_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('action', models.CharField(choices=[('requested', 'requested'), ('enrolled', 'enrolled'), ('completed', 'completed'), ('failed', 'failed')], max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.student')),
            ],
        ),
        migrations.CreateModel(
            name='course_instructor_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('action', models.CharField(choices=[('joined', 'joined'), ('left', 'left')], max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('attendance_verbose', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='attendance date')),
                ('entry_timestamp', models.DateTimeField(verbose_name='timestamp of entry')),
                ('image', models.ImageField(upload_to='', verbose_name='image')),
                ('is_extra', models.BooleanField(default=False, verbose_name='extra class')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('roll_calls', models.ManyToManyField(to='profiles.student')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.period_slot')),
            ],
        ),
    ]
