<<<<<<< HEAD
# Generated by Django 3.0.3 on 2020-03-28 07:15
=======
# Generated by Django 3.0.3 on 2020-03-27 16:32
>>>>>>> 1eaca80e6ff925e15873b7ce429f260aa7d0c3fa

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('institution', '0001_initial'),
        ('profiles', '0001_initial'),
=======
        ('profiles', '0001_initial'),
        ('institution', '0002_auto_20200327_2202'),
>>>>>>> 1eaca80e6ff925e15873b7ce429f260aa7d0c3fa
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
<<<<<<< HEAD
                ('name', models.CharField(max_length=20, unique=True, verbose_name='course name')),
                ('course_id', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True, verbose_name='course id')),
=======
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='course name')),
                ('course_id', models.CharField(max_length=5, unique=True, verbose_name='course id')),
>>>>>>> 1eaca80e6ff925e15873b7ce429f260aa7d0c3fa
                ('status', models.CharField(choices=[('floating', 'floating'), ('closed', 'closed')], max_length=20, verbose_name='status')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.departements')),
                ('pre_requisites', models.ManyToManyField(related_name='_course_pre_requisites_+', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='time_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.ManyToManyField(to='courses.course')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.period_slots')),
            ],
        ),
        migrations.CreateModel(
            name='course_ta_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('action', models.CharField(choices=[('joined', 'joined'), ('left', 'left')], max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.ta')),
            ],
        ),
        migrations.CreateModel(
            name='course_student_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('action', models.CharField(choices=[('requested', 'requested'), ('enrolled', 'enrolled'), ('completed', 'completed'), ('failed', 'failed')], max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.students')),
            ],
        ),
        migrations.CreateModel(
            name='course_instructor_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('action', models.CharField(choices=[('joined', 'joined'), ('left', 'left')], max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='attendance',
            fields=[
<<<<<<< HEAD
                ('attendance_verbose', models.CharField(max_length=50, primary_key=True, serialize=False)),
=======
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
>>>>>>> 1eaca80e6ff925e15873b7ce429f260aa7d0c3fa
                ('date', models.DateField(verbose_name='attendance date')),
                ('entry_timestamp', models.DateTimeField(verbose_name='timestamp of entry')),
                ('image', models.ImageField(upload_to='', verbose_name='image')),
                ('is_extra', models.BooleanField(default=False, verbose_name='extra class')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('roll_calls', models.ManyToManyField(to='profiles.students')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.period_slots')),
            ],
        ),
    ]
