# Generated by Django 3.0.3 on 2020-03-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='course name'),
        ),
        migrations.AlterField(
            model_name='course',
            name='pre_requisites',
            field=models.ManyToManyField(blank=True, null=True, related_name='_course_pre_requisites_+', to='courses.course'),
        ),
    ]
