# Generated by Django 3.0.3 on 2020-03-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200327_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='pre_requisites',
            field=models.ManyToManyField(blank=True, related_name='_course_pre_requisites_+', to='courses.course'),
        ),
    ]
