# Generated by Django 3.0.3 on 2020-03-30 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('department', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='period_slot',
            fields=[
                ('day', models.CharField(choices=[('monday', 'monday'), ('tuesday', 'tuesday'), ('wednesday', 'wednesday'), ('thursday', 'thursday'), ('friday', 'friday'), ('saturday', 'saturday'), ('sunday', 'sunday')], max_length=10, verbose_name='week day')),
                ('start_time', models.TimeField(verbose_name='slot start time')),
                ('end_time', models.TimeField(verbose_name='slot end time')),
                ('slot_verbose', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='public_announcement',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
                ('info', models.TextField()),
            ],
        ),
    ]
