# Generated by Django 3.0.3 on 2020-03-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='departements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='period_slots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'monday'), ('tuesday', 'tuesday'), ('wednesday', 'wednesday'), ('thursday', 'thursday'), ('friday', 'friday'), ('saturday', 'saturday'), ('sunday', 'sunday')], max_length=10, verbose_name='week day')),
                ('start_time', models.TimeField(verbose_name='slot start time')),
                ('end_time', models.TimeField(verbose_name='slot end time')),
            ],
        ),
        migrations.AlterField(
            model_name='public_announcements',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='public_announcements',
            name='info',
            field=models.TextField(),
        ),
    ]
