# Generated by Django 3.0.3 on 2020-03-29 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('profiles', '0001_initial'),
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='departements',
            new_name='department',
        ),
        migrations.RenameModel(
            old_name='period_slots',
            new_name='period_slot',
        ),
        migrations.RenameModel(
            old_name='public_announcements',
            new_name='public_announcement',
        ),
    ]
