# Generated by Django 3.0.3 on 2020-03-02 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20200303_0127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_faculty',
            new_name='faculty',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_gsadmin',
            new_name='gsadmin',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_student',
            new_name='student',
        ),
    ]
