<<<<<<< HEAD
# Generated by Django 3.0.3 on 2020-03-28 07:15
=======
# Generated by Django 3.0.3 on 2020-03-27 16:32
>>>>>>> 1eaca80e6ff925e15873b7ce429f260aa7d0c3fa

from django.db import migrations, models
import django.db.models.deletion
import profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('institution', '0001_initial'),
=======
        ('institution', '0002_auto_20200327_2202'),
>>>>>>> 1eaca80e6ff925e15873b7ce429f260aa7d0c3fa
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
<<<<<<< HEAD
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True, verbose_name='email ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='Full name')),
                ('dob', models.DateField(verbose_name='Date of birth')),
                ('doj', models.DateField(verbose_name='Date of join')),
                ('image', models.ImageField(upload_to=profiles.models.content_file_name, verbose_name='profile image')),
                ('status', models.BooleanField(default=False, verbose_name='account status')),
                ('description', models.TextField(null=True, verbose_name='breif description')),
                ('qualification', models.CharField(choices=[('student', 'student'), ('ta', 'ta'), ('instructor', 'instructor')], default='student', max_length=10, verbose_name='qualification')),
=======
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('full_name', models.CharField(max_length=50)),
                ('dob', models.DateField(verbose_name='dob')),
                ('doj', models.DateField(verbose_name='doj')),
                ('image', models.ImageField(upload_to=profiles.models.content_file_name, verbose_name='image')),
                ('status', models.BooleanField(default=False, verbose_name='status')),
                ('description', models.TextField(null=True, verbose_name='description')),
                ('qualification', models.CharField(choices=[('student', 'student'), ('ta', 'ta'), ('instructor', 'instructor')], default='student', max_length=10, verbose_name='Qualification')),
>>>>>>> 1eaca80e6ff925e15873b7ce429f260aa7d0c3fa
                ('password', models.TextField(verbose_name='password')),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
<<<<<<< HEAD
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='profiles.user')),
                ('semester', models.IntegerField(verbose_name='Current semester')),
=======
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='profiles.user')),
>>>>>>> 1eaca80e6ff925e15873b7ce429f260aa7d0c3fa
            ],
        ),
        migrations.CreateModel(
            name='ta',
            fields=[
<<<<<<< HEAD
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='profiles.user')),
=======
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='profiles.user')),
>>>>>>> 1eaca80e6ff925e15873b7ce429f260aa7d0c3fa
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.departements')),
            ],
        ),
        migrations.CreateModel(
            name='instructor',
            fields=[
<<<<<<< HEAD
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='profiles.user')),
=======
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='profiles.user')),
>>>>>>> 1eaca80e6ff925e15873b7ce429f260aa7d0c3fa
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.departements')),
            ],
        ),
    ]
