# Generated by Django 3.0.3 on 2020-03-28 07:15

from django.db import migrations, models
import django.db.models.deletion
import profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True, verbose_name='email ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='Full name')),
                ('dob', models.DateField(verbose_name='Date of birth')),
                ('doj', models.DateField(verbose_name='Date of join')),
                ('image', models.ImageField(upload_to=profiles.models.content_file_name, verbose_name='profile image')),
                ('status', models.BooleanField(default=False, verbose_name='account status')),
                ('description', models.TextField(null=True, verbose_name='breif description')),
                ('qualification', models.CharField(choices=[('student', 'student'), ('ta', 'ta'), ('instructor', 'instructor')], default='student', max_length=10, verbose_name='qualification')),
                ('password', models.TextField(verbose_name='password')),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='profiles.user')),
                ('semester', models.IntegerField(verbose_name='Current semester')),
            ],
        ),
        migrations.CreateModel(
            name='ta',
            fields=[
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='profiles.user')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.departements')),
            ],
        ),
        migrations.CreateModel(
            name='instructor',
            fields=[
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='profiles.user')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.departements')),
            ],
        ),
    ]
